### ISSUE TITLE
handler has return type <class 'NoneType'> error, when returning None

### ISSUE THREAD

**Issue by zakybilfagih** [Ananto30/zero#44]
When creating a handler with the return type hint None
```python
@app.register_rpc
def send_mail(payload: SendEmailPayload) -> None:
    // send mail
```

I got this error

```
Traceback (most recent call last):
  File "/home/mackarelfish/Documents/huey_server/main.py", line 14, in <module>
    @app.register_rpc
     ^^^^^^^^^^^^^^^^
  File "/home/mackarelfish/Documents/huey_server/env/lib/python3.11/site-packages/zero/client_server/server.py", line 82, in register_rpc
    type_util.verify_function_return_type(func)
  File "/home/mackarelfish/Documents/huey_server/env/lib/python3.11/site-packages/zero/utils/type_util.py", line 139, in verify_function_return_type
    raise TypeError(
TypeError: send_mail has return type <class 'NoneType'> which is not allowed; allowed types are: 
None
<class 'bool'>
<class 'int'>
<class 'float'>
<class 'str'>
<class 'bytes'>
<class 'bytearray'>
<class 'tuple'>
typing.Tuple
<class 'list'>
typing.List
<class 'dict'>
typing.Dict
<class 'set'>
typing.Set
<class 'frozenset'>
typing.FrozenSet
<class 'datetime.datetime'>
<class 'datetime.date'>
<class 'datetime.time'>
<class 'uuid.UUID'>
<class 'decimal.Decimal'>
<enum 'Enum'>
<enum 'IntEnum'>
<function dataclass at 0x7f05fd4993a0>
typing.Any
typing.Union
typing.Optional
```

Fixed this by wrapping None with type(None) here
https://github.com/Ananto30/zero/blob/da84cf2854f99baff9293cf2962a249aa21dcb06/zero/utils/type_util.py#L11C14-L14

**Comment by Ananto30** [comment]
Yes, this is intentional. It's a debate but for now, you always have to return something from the server. If you are executing a command rather a query, you can return a bool (true or false). Just like the redis library in python.

**Comment by zakybilfagih** [comment]
I see, maybe we can update the docs then? Created a PR for this!
